import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/MainHeader";
import Footer from "@/components/Footer";

import localFont from "next/font/local";
import {
  Lexend,
  Oswald,
  Geologica,
  Playfair_Display,
  Nunito_Sans,
} from "next/font/google";
import FloatingWhatsApp from "@/components/FloatingWhatsApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const MontserratFont = Nunito_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body className={` ${MontserratFont.className} antialiased`}>
        <MainHeader />
        {children}
        <Footer />
        <FloatingWhatsApp />
      </body>
    </html>
  );
}
